server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  api-docs:
    title: "Backend API Documentation"
    description: "API documentation for the backend services."
    version: OPENAPI_3_1
    path: /v3/api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui
    enabled: true